sucuri.php
The log exporter allows admin users to force the plugin to send a copy of the data generated when WordPress triggers an event that is being monitored by the plugin, the file path should not be publicly accessible, and the file must not exists to prevent unwanted modifications to the current files in the server as a malicious admin could reset the content of arbitrary files at will. This pull-request adds validations to check if the specified file path exists, if the parent directory is writable, and then creates the file per user requests and set two entries in the options table to track the status of the tool _(enabled or disabled)_.
=> Added automatic log exporter file creation

sucuri.php
When a HTTP request fails the plugin tries to store the data for future retries, unfortunately the current code had a dependency in one of the data entries containing the timestamp of the initial execution used to keep the audit logs in chronological order, some API endpoints do not provide this data and were making the code throw some warnings; [this commit](https://github.com/Sucuri/sucuri-wordpress-plugin/commit/c8eda72) fixes the issue.
The directory separator for the main folder where the plugin stores the security logs and some temporary data was using a hardcoded version of the forward slash character which was not compatible with the Windows server configuration; [this commit](https://github.com/Sucuri/sucuri-wordpress-plugin/commit/44a8720) fixes that issue.
The URL for the Ajax …
=> Fixed issues with URLs and broken API requests

sucuri.php
When the plugin is retrieving one or more settings it tries to read them from a plain text file located _(by default)_ at _"/wp-content/uploads/sucuri/sucuri-settings.php"_, this is a JSON encoded file with an array where the keys are the names of the options. If the option is found in the file then it immediately returns its value, otherwise it continues with the search in the database, if it finds it then deletes the option from there and writes its value in the JSON file for future usage. If at the end the option is not found in the JSON file nor in the database then it returns a default value hardcoded in the code.
This pull-request fixes a bug that was going to cause a deletion of the non-plugin options if they were not in the JSON file, the deletion was intended to be executed only …
=> Fixed get_option method when the value is in the database

sucuri.php
There is a button in the general settings page that allows users to reset the configuration of the plugin, this basically deletes all the options prefixed with _"sucuriscan"_ from the database and the JSON file. However, since the data returned from the database is actually an object and the one returned from the plain text file is a string the function that is supposed to delete the data gets confused and throws a warning about the different data types. This PR fixes this minor issue.
Additionally, in the cache library used to read and parse the content of the security logs was missing a forward slash to separate the directory path where the user decided to store the logs and the file name for the cache.
=> Fixed minor issues with the data storage getter

sucuri.php
Before the release of WordPress 4.6 the core developers decided to introduce a new object _"WP_HTTP_Requests_Response"_ to hold the relevant information after a HTTP request. There are multiple blocks of code in the plugin that rely in the format old object, this pull-request drops the dependencies of the built-in functions _"wp_remote_get"_ and _"wp_remote_head"_ to be able to control the backward compatibility with old WordPress installations.
Additionally, to simplify the automated tests we have modified the admin notices to throw a generic exception when a constant _"SUCURISCAN_THROW_EXCEPTION"_ is defined as a boolean _True_, with this we can expand the coverage of the unit-tests to all the functions that were generating admin notices with errors and info messages after the …
=> Backward compatibility for HTTP requests and granular unit-tests

sucuri.php
Most of the HTTP requests executed through out the entire code base to communicate with the Sucuri API service and the 3rd-party services provided by WordPress have a low connection timeout, the plugin assumes that the service is not available after five seconds that can be configured by the user from the settings page. However, the connection with the SiteCheck API service takes around ~20 secs when a fresh scan is requested, because of this the plugin needs to force a different connection timeout of around ~30 secs that can also be configured from the settings page.
=> Fixed connection timeout for the SiteCheck web scans

sucuri.php
Added alternative to the built-in PHP function http_build_query. Some PHP installations with different encoding or with different language _(German for example)_ might produce an unwanted behavior when building an URL, because of this we decided to write our own URL query builder to keep control of the output. In the example below we can see how a mis-configured PHP installation returns an invalid string with 75 characters using _"http_build_query"_ when it actually has 59, this pull-request fixes this broken behavior using a custom iterator to concatenate the array with the correct length.
```
array(5) {
["jwqzh"] => string(5) "6gzy2"
["4iy5w"] => string(5) "hylnv"
["2wqww"] => string(5) "wsq2c"
["mm4rn"] => string(5) "yhr6l"
["22e02"] => string(5) "sefay"
}
string(75) …
```
=> Fixed HTTP query builder using custom array iterator

inc/tpl/bsidebar.html.tpl, inc/tpl/settings-apiservice-handler.html.tpl, inc/tpl/settings-apiservice.html.tpl, sucuri.php, uninstall.php
This pull-request adds a secondary mechanism to rescue the HTTP requests sent by the plugin to external API services using raw sockets via the built-in PHP function _"fsockopen"_. This is necessary for websites without _"libcurl"_.
=> Added function to rescue HTTP requests using sockets

readme.txt, sucuri.php
`CURLOPT_FOLLOWLOCATION` cannot be activated when _"safe_mode"_ is enabled or an _"open_basedir"_ is set. This pull-request adds a condition around this option to prevent this failure in the execution of the HTTP requests, alternative the user can go to the _"API Service"_ panel located in the plugin' settings page and change the _"API Request Handler"_ to force the plugin to use the alternate interfaces instead of Curl.
=> Fixed Curl redirection follower with safe_mode enabled

readme.txt, sucuri.php
The current code is failing silently when the user tries to generate, recover, or manually set an API key to fully activate the plugin when the data storage folder is not writable. This pull-request adds a warning message on `_POST` requests associated with the management of the key _(specifically in the general settings page)_ advising the user to grant write privileges in the directory set as the data storage, or the to the settings file.
Apparently the WordPress class _"WP_Rewrite"_ is not available all the time as it used to be in previous versions, this provokes a warning in the _"Site Info"_ page when the panel used to check the integrity of the access control file is rendered, this is because the class is being used to retrieve the default rules that Wordpress inserts in the main …
=> Added error message when storage is not writable

inc/tpl/settings-datastorage-files.snippet.tpl, inc/tpl/settings-general-datastorage.html.tpl, readme.txt, sucuri.php
The naming of the function used to check if the user has decided to keep using the database to store the plugin's settings was ambiguous; this adds a new function with a clear definition of the boolean check.
After complains from some users we decided to revert the default value for the availalbe plugin and themes email alerts back to "disabled" as we found that some web agencies have several WordPress websites running with outdated software and possibly not willing to update them all, so the notifications are being seen as annoying.
The audit logs is not responding if PHP is configured to be strict with the warnings, there is a missing initializator for an array key that was used to concatenate strings, as well as a read access to a non-existent object property.
I have found that the …
=> Added new version 1.8.2

src/integrity.lib.php
This pull-request fixes a problem with the WordPress core integrity panel where files were not being marked as fixed, restored, nor deleted because the action that was executed was different than the flag that was marking each file, this flag was not supposed to be used as a check. This commit fixed this problem for all cases.
=> Fix handling of the actions in the core integrity checks

inc/css/styles.css, inc/tpl/auditlogs.html.tpl, inc/tpl/auditlogs.snippet.tpl, src/auditlogs.lib.php, src/pagehandler.php, src/settings-general.php
The data in the _"Audit Logs"_ panel is cached for 600 seconds _(as of the time of writing this)_ to reduce the number of HTTP requests sent to the API service. However, some people may want to see updated data depending on how often they check the plugin's dashboard. For this, I have added a button that allows them to refresh the cache and load the new logs. This pull-request also reduces the margins between each log in the interface to make them more compact.
=> Add message and button to reset the audit logs cache

src/option.lib.php
Allows site owners and platforms to define their own option defaults on fresh installs.
=> Make default plugin options filterable

src/option.lib.php
Greatly reduce calls to the file system by storing all options in object cache for the life of the request.
=> Store options in object cache

src/cli.lib.php, sucuri.php
This WP-CLI command will allow site owners and platforms to programmatically register a site with the Sucuri API. If the site is already registered, an email will be sent to the site owner.
```sh
$ wp sucuri register
API key: 99e656abef7a123d1cffe73f91ba63702
Success: The API key for your site was successfully generated and saved.
```
```sh
$ wp sucuri register 99e656abef7a123d1cffe73f91ba63702
Success: The API key for your site was successfully saved.
```
```sh
$ wp sucuri register
Error: We already have an API key created for this site. It has been sent to the email admin@example.com for recovery.
```
=> WP-CLI command for API registration

inc/css/styles.css, inc/js/scripts.js, inc/tpl/lastlogins-failedlogins.html.tpl, inc/tpl/lastlogins-failedlogins.snippet.tpl, inc/tpl/notification-pretty.html.tpl, inc/tpl/notification-simple.html.tpl, inc/tpl/settings-alerts-ignore-posts.html.tpl, src/auditlogs.lib.php, src/cli.lib.php, src/hook.lib.php, src/interface.lib.php, src/lastlogins-failed.php, src/mail.lib.php, src/option.lib.php, src/settings-alerts.php, src/settings-general.php, src/sucuriscan.lib.php, sucuri.php
* Add support to export and import trusted IP addresses
* Add reverse ip address in all email alerts from visitor
* Add support for WP-CLI, initially with a command to generate the API key
If an user is replicating the settings from website A into website B and the API key is among the options that can be imported, this will force website B to send all the security logs to the API service as if the events were triggered in website A. An user can always request a copy of the API key from the general settings so having this piece of data in the export list is not necessary.
After the adoption of [Prettier](https://prettier.io), the opinionated code formatter for JavaScript files, I decided to fix the content of the main CSS and JS files, as well as the regeneration of the cache for the …
=> Multiple improvements in the settings page and support for WP-CLI

src/settings-integrity.php
In the settings page, under the panel with the list of files marked as fixed from the WordPress Integrity tool, there is a button to reset the list. The button is part of a form that is supposed to send a POST parameter named `"sucuriscan_ corefile_path"` as an array, the plugin walks through the array and removes the files marked as fixed from the cache. However, when the request is missing the parameter, the plugin fails to process the request because the iterator is expecting an array but is receiving a `"null"`.
=> Fix invalid array when resetting the integrity cache

inc/tpl/sitecheck-recommendations.html.tpl, src/sitecheck.lib.php
When SiteCheck detects that the website is missing one or more recommended security headers, the plugin displays an additional box on the right side of the dashboard with a link to the KB website explaining the important of such header(s). However, there is no positive feedback after the user adds the missing security headers and refreshes the malware scan cache. This pull-request adds checkmarks for the visible headers to notify the user that they have been set correctly.
=> Add positive confirmation for existing security headers

sucuri.php
This is part of an on-going investigation to determine what is the cause of the random deletion of the plugin settings that some users have been reporting in the WordPress forums. The discussion is being tracked here:
https://wordpress.org/support/topic/sucuri-email-notifications-resetting/
=> Add logs in the function used to deactivate and uninstall the plugin

src/base.lib.php
When the user visits **“Settings > Scanner > Scheduled Tasks”** the plugin calls a function provided by WordPress called `wp_get_schedules` which is supposed to return a list with all the active scheduled tasks (aka. cronjobs). According to the documentation, each item in the list has an attribute with the arguments that will be passed to the corresponding functions that will run once the cronjob is executed. This attribute is supposed to be an array, but in some cases the value uses a different data type which breaks the implode function.
=> Add additional type check in custom array implode

inc/tpl/settings-hardening-whitelist-phpfiles.html.tpl, src/base.lib.php, src/fileinfo.lib.php, src/settings-hardening.php, sucuri.php
When the website owner decides to rename the content or uploads directory, they find that the plugin stops offering the option to whitelist the execution of PHP files in the aforementioned folders, this is because the path is hardcoded in the HTML files. This pull-request also includes the replacement of some hardcoded references to the `wp-content` directory with the standard `WP_CONTENT_DIR` constant.
Reference: https://wordpress.org/support/topic/i-cannot-use-whitelist-blocked-php-files-function/
=> Add dynamic core directories in the hardening whitelist option

inc/tpl/settings-scanner-cronjobs.html.tpl, src/pagehandler.php, src/settings-scanner.php
There have been cases where a website contains dozens of scheduled tasks which affect the load time of the settings page because the interpreter has to wait for all the items in the cronjob list to be processed before the page is rendered. This commit fixes this problem by loading the data via Ajax.
Reference: https://wordpress.org/support/topic/setting-page-is-blank-3/
=> Modify scheduled tasks panel to load the table via Ajax

src/integrity.lib.php
Since version 5.0, WordPress stores some JSON files in `/wp-content/languages`. Unfortunately, these aren’t being excluded from the core integrity checks in the way that `.mo` and `.po` files are, resulting in false positives.
Reference: https://wordpress.org/support/topic/not-compatible-with-the-new-javascript-i18n-support-in-wordpress-5-0/
=> Ignore new JSON based language files after WordPress 5.x

src/template.lib.php
- Multiple matches per line should be supported
- Regex replacement was unnecessary overhead
=> Fix regex in template string replacement

src/wordpress-recommendations.lib.php
I noticed that the admin/administrator lookup was not working as expected prior WordPress 4.7. This was because the `login` param wasn't added until 4.7 (https://github.com/WordPress/WordPress/commit/e96c617c03a17e1de11c64488a394d225d7a4a0f#diff-a11b398dd46cc2d79f3f2072ede871c0).
This PR fixes the lookup!
=> Fix admin/administrator username lookup for WordPress versions prior 4.7

src/wordpress-recommendations.lib.php
The directory hardening recommendation was shown even if the site was behind the firewall, causing different information between the recommendation box and the hardening settings page. This PR fixes that.
=> Fix directory hardening recommendation

src/base.lib.php
This PR slightly updates how the plugin checks if a website if behind the Sucuri Firewall.
It removes the checks against `SucuriScanFirewall::getKey()` and `$_SERVER['REMOTE_ADDR']`. I decided to remove said checks because the `HTTP_X_SUCURI_CLIENTIP` is what **really** tell us if the traffic comes from the firewall, or not.
Zip file: [sucuri-scanner.zip](https://github.com/Sucuri/sucuri-wordpress-plugin/files/4052054/sucuri-scanner.zip)
=> Update how the plugin verifies the firewall status

src/auditlogs.lib.php
The total entries of the logs is already available through the `$auditlogs` variable.
Lines 258 and 259 were causing reading and parsing of the file twice, making it three in total.
Zip file with these changes: [sucuri-scanner.zip](https://github.com/Sucuri/sucuri-wordpress-plugin/files/4062827/sucuri-scanner.zip)
=> Remove unnecessary code slowing down retrieval of auditlogs

src/sitecheck.lib.php
Basically we'll ask Sitecheck to re-scan the site if:
1. Local cache is invalid
2. User requested it with the "Refresh Malware Scan" link
=> Force Sitecheck to re-scan the site if the user clicks on "Refresh Malware Scan"

readme.txt, src/event.lib.php
That constant was introduced only on WP 4.4.0:
https://developer.wordpress.org/reference/functions/wp_initial_constants/
=> Fix notice caused by lack of MONTH_IN_SECONDS constant

.github/workflows/end-to-end-tests.yml, cypress/integration/sucuri-scanner-firewall.js, inc/tpl/base.html.tpl, inc/tpl/firewall-ipaccess.html.tpl, inc/tpl/firewall-settings.html.tpl
This PR adds a new test suite that evaluates whether the plugin can connect or not to Sucuri's API to register a WAF API key, see audit logs from the plugin, add a new IP address to the blocklist and clear cache when a post/page is created or updated.
The only tricky part about this is that we require a real API key to make this work, so this test suite requires the secret `WAF_API_KEY` to be set, and if not, this test suite will be skipped.
PS. Our e2e tests are failing because of an issue with the `@wordpress/env` package: https://github.com/WordPress/gutenberg/issues/29752
=> Add Cypress e2e tests for Firewall tab

.github/workflows/end-to-end-tests.yml, .gitignore, package-lock.json, package.json
This PR updates `@wordpress/env` and allows the e2e tests to run in different PHP versions. This is going to pave the way to adding support for PHP 8.
=> Fix e2e tests

src/hook.lib.php
Resolves an issue in PHP8 where a required parameter follows an optional parameter in a function declaration. #104
```
PHP Deprecated:  Required parameter $old_user_data follows optional parameter $id in /sucuri-scanner/src/hook.lib.php on line 999
```
=> Fix required parameter follows optional parameter issue

src/sitecheck.lib.php
This commit fixes an uncaught TypeError when the value passed to `count()` is  not an array.
Closes #113
=> Fix uncaught TypeError

src/settings-hardening.php
This commit fixes a notice when `DISALLOW_FILE_EDIT` has already been defined with a falsy value.
Closes #106
=> Fix DISALLOW_FILE_EDIT related notice

.github/workflows/end-to-end-tests.yml, .gitignore, Makefile, cypress.json.example, cypress/integration/sucuri-scanner.js, package-lock.json, package.json, src/base.lib.php, src/installer-skin-legacy.lib.php, src/installer-skin.lib.php, src/settings-posthack.php
**Summary:**
* Update CI workflow and Cypress to use the test env provided by [@wordpress/env](https://www.npmjs.com/package/@wordpress/env)
* Update CI workflow to also run tests on PHP 8
* Fixed incompatible method signature error happening in PHP 8 (`feedback` method on the `SucuriScanPluginInstallerSkin class`). More about that [here](https://wiki.php.net/rfc/lsp_errors).
* Fixed logic error when updating how frequent the secret keys updater runs
* Updated the Cypress tests so they work in older versions of WordPress
=> Support for PHP 8

src/cache.lib.php
This commit silences the warning [fopen](https://www.php.net/manual/en/function.fopen.php) emits upon failure (e.g. the file requested does not exist).
=> Silence fopen warning

.gitignore, src/cache.lib.php, tests/CacheTest.php
This commit fixes the `PHP Fatal error Uncaught ValueError: Path cannot be empty in src/cache.lib.php:407` error.
=> Fix "Path cannot be empty" error

cypress/integration/sucuri-scanner-firewall.js, inc/css/styles.css, inc/tpl/firewall-clearcache.html.tpl, src/firewall.lib.php
This PR adds an option to clear cache by path. It also updates the clear cache page description text to make it easier to understand the differences between the available options.
Default View
After Cache Cleared
=> Added option to clear cache by path

Makefile, cypress.json.example, cypress/integration/sucuri-scanner-firewall.js, cypress/integration/sucuri-scanner.js, cypress/support/commands.js, cypress/support/index.js, package-lock.json, package.json
This PR addresses the e2e tests failures:
- Fixed e2e tests setup (e2e-prepare)
- Fixed scanner e2e tests
- Skips the scanner e2e tests that require write permissions on the test container WP directories. This is temporary until the test suite is updated to leverage a custom docker setup or [wp-env](https://github.com/WordPress/gutenberg/tree/trunk/packages/env) addresses this [limitation](https://github.com/WordPress/gutenberg/issues/22515)
=> Fixed scanner e2e tests

.wp-env.json, cypress/integration/sucuri-scanner.js, inc/css/styles.css, inc/tpl/settings-apiservice-status.html.tpl, src/event.lib.php, src/option.lib.php, src/settings-apiservice.php, sucuri.php
This PR removes the `https://wordpress.sucuri.net/api/` dependency, since this service has been discontinued until further notice. User who have their custom API to use in place of `https://wordpress.sucuri.net/api/` can still use the functionality by  adding the API endpoint as `SUCURISCAN_API_URL` on the `wp-config.php` file.
=> Removed wordpress.sucuri.net API dependency

src/hardening.lib.php
Hello,
If Wordpress Core files are located in a subdirectory, the path to .htaccess file is incorrect.
Sucuri should not use `ABSPATH` to locate files but the [get_home_path()](https://developer.wordpress.org/reference/functions/get_home_path/) function 
I think this fix should also fix issue #119
=> Fix wrong path to .htaccess

inc/css/styles.css, inc/tpl/settings-apiservice-status.html.tpl, readme.txt, src/interface.lib.php, src/settings-apiservice.php, sucuri.php
This PR brings in more fixes for the API service functionality so as to provide more elaborate errors and alerts messaging for all of the API service status.
=> Fixed API service messaging

src/mail.lib.php, src/settings-alerts.php
This PR fixes an issue whereby critical failures `PHP Fatal errors` while dispatching email notifications were bubbling up as `500s` and blocking users. 
It also adds a notification shown when the testing email notification fails and a log item for email notification failures.
=> Fix mail error handling
