Sucuri/sucuri-wordpress-plugin

- sucuri.php
The alternate interface used to rescue the HTTP requests executed using Curl was not supporting HTTP responses with the _"Transfer-Encoding: chunked"_ header, this was forcing the plugin to believe that the HTTP responses were malformed because of the extra information returned by the socket reader used to determine the size of the next chunk. This pull-request fixes this behavior.
> Added support for chunked transfer encoding via sockets

- inc/tpl/bsidebar.html.tpl
- inc/tpl/malwarescan.html.tpl
- readme.txt
- sucuri.php
= 1.8.3 =
* Removed goo.gl links
* Fixed fatal error when PHPMailer failed
* Fixed incorrect selected value in settings
* Added SiteCheck for arbitrary domain
* Various code cleanup
> 1.8.3 Release Candidate

- readme.txt
- src/option.lib.php
- sucuri.php
This change allows other developers to set the initial value of the settings programmatically.
> Add filter to allow automatic configuration of the settings

- src/cli.lib.php
Objective: Use the CLI to manage which files are ignored during integrity checks.
```
$ wp sucuri integrity ignore wp-content/foo.php
Success: 'wp-content/foo.php' file successfully ignored.
$ wp sucuri integrity unignore wp-content/foo.php
Success: 'wp-content/foo.php' file successfully unignore.
```
This is just one small step, I think down the road a good goal will be to allow Admins to do anything from CLI that they can do from the browser (e.g. restore files, delete files, run scans, set hardening options, etc.).
> Add new command for integrity

- src/sitecheck.lib.php
Allows managed hosts to customize the display of their brand name.
> Allow hosting details display to be filterable

- readme.txt
- src/wordpress-recommendations.lib.php
This PR removes the 2fa and backup plugin recommendations from 1.8.22
> Remove backups and 2fa security recommendations

- src/sitecheck.lib.php
Update the Sitecheck's recommendation box to not show passing checks.
> Update the "Recommendations" box to not show passing checks

- readme.txt
More information here: https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/#section-details
> Bump compatibility to WordPress version 5.5.3

- .gitattributes
- .gitignore
- Makefile
- composer.json
- composer.lock
- phpunit.xml
- src/cache.lib.php
- tests/CacheTest.php
- tests/autoload.php
- tests/fixtures/sucuri-auditqueue.php
**Summary:**
- Replace `SucuriScanFileInfo::fileLines` with `fopen/fgets`, which
doesn't load the whole content into memory
- Add unit tests
> Reduce memory requirements when reading a log file

- .gitignore
- lang/sucuri-scanner.pot
- readme.txt
- sucuri.php
This PR:
* Ignores `.vscode/settings.json`
* Bumps plugin version to 1.8.27
* Updates changelog
> Bump plugin version

- .github/workflows/end-to-end-tests.yml
- .github/workflows/unit-tests.yml
- readme.txt
This PR:
* Fixes typo in readme
* Adds a new workflow for the unit tests.
* Updates the workflow for the e2e tests
> Update workflow & fix typo

- src/cron.lib.php
- src/event.lib.php
- src/settings-posthack.php
> Fix "Empty wp-config file after automatic secret key updates"

- src/hook.lib.php
This PR fixes an issue with referrer checks being executed too early and causing some core functionalities to fail.
> Fixed early referrer checks

- .gitignore
- inc/tpl/base.html.tpl
- inc/tpl/lastlogins-all.snippet.tpl
- readme.txt
- src/integrity.lib.php
- src/lastlogins.php
- sucuri.php
This PR:
* Update list of Sucuri cleanup files
* Update successful login screen to show date time
> Update list of Sucuri cleanup files; Update successful logins creen

- readme.txt
Update readme with 1.8.41 changes
> Update readme with 1.8.41 changes

- Makefile
- inc/css/styles.css
- inc/tpl/sitecheck-malware.html.tpl
- lang/sucuri-scanner.pot
- package-lock.json
- readme.txt
- src/strings.php
- sucuri.php
This PR:
* Update malware cleanup notification
> [1.8.42] Update malware cleanup notification

- Makefile
- cypress/e2e/sucuri-scanner.cy.js
- inc/css/styles.css
- inc/tpl/integrity-incorrect.html.tpl
- inc/tpl/integrity.html.tpl
- lang/sucuri-scanner.pot
- package.json
- readme.txt
- src/integrity.lib.php
- src/template.lib.php
- sucuri.php
This PR:
* Improve how the WordPress integrity tool displays added, modified, and removed files
> 1.9.2 Improve how the WordPress integrity tool displays added, modified, and removed files 

- lang/sucuri-scanner.pot
- readme.txt
- sucuri.php
> Version 1.9.3

- lang/sucuri-scanner.pot
- readme.txt
- src/integrity.lib.php
- sucuri.php
This PR fixes an undefined warning in PHP 8.
> Fix warning in PHP 8

- .github/workflows/unit-tests.yml
- Makefile
- composer.json
- composer.lock
- cypress/e2e/sucuri-scanner.cy.js
- inc/tpl/settings-hardening-allowlist-phpfiles.html.tpl
- lang/sucuri-scanner.pot
- readme.txt
- src/hardening.lib.php
- src/settings-hardening.php
- sucuri.php
- tests/HardeningTest.php
- tests/autoload.php
- tests/constants.php
This PR:
* Updates the allowlist functionality for the hardening section
> 1.9.5 Update allowlist functionality for hardening section

- cypress/e2e/sucuri-scanner.cy.js
- src/hardening.lib.php
This PR:
* Fix bug causing rules to have double slashes
> 1.9.5 Fix bug causing rules to have double slashes

- cypress/e2e/sucuri-scanner.cy.js
- inc/css/styles.css
- inc/tpl/auditlogs-filter.snippet.tpl
- inc/tpl/auditlogs-filters.snippet.tpl
- inc/tpl/auditlogs.html.tpl
- inc/tpl/sitecheck-malware.html.tpl
- lang/sucuri-scanner.pot
- readme.txt
- src/api.lib.php
- src/auditlogs.lib.php
- src/template.lib.php
- sucuri.php
- tests/AuditlogsTest.php
- tests/CacheTest.php
- tests/autoload.php
- tests/constants.php
- tests/fixtures/sucuri-auditqueue.php
This PR:
* Added support for filters in the audit logs
* Updated messaging for infected sites
> 1.9.6 Add support for filtering auditlogs

- lang/sucuri-scanner.pot
- readme.txt
- src/api.lib.php
- src/event.lib.php
- sucuri.php
This PR:
* Fix bug deleting failed logins.
* Fix bug causing WAF blocks due user-agent containing domain names with specific words.
> Fix deleting logs & update user-agent for external requests

- cypress/e2e/sucuri-scanner.cy.js
- inc/css/dark.css
- inc/css/light.css
- inc/css/shared.css
- inc/tpl/base.html.tpl
- lang/sucuri-scanner.pot
- package-lock.json
- package.json
- readme.txt
- src/interface.lib.php
- src/option.lib.php
- src/pagehandler.php
- src/template.lib.php
- sucuri.php
> Add theme toggle
